apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: multi-intent
  namespace: multi-intent
  labels:
    app.kubernetes.io/name: multi-intent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-intent
