apiVersion: v1
kind: Service
metadata:
  name: multi-intent
  namespace: multi-intent
  labels:
    app.kubernetes.io/name: multi-intent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: multi-intent
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
